import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useCreateFriendlyMatch } from '../hooks/friendlyHooks'
import type { CreateFriendlyMatchRequest, FriendlyEventType, FriendlyFormat } from '../types/friendly.types'
import { friendlyDetailsPath, validateFriendlyMatch } from '../utils/friendlyValidation'

export const FriendlyCreatePage = () => {
  const navigate = useNavigate(); const mutation = useCreateFriendlyMatch()
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [eventType, setEventType] = useState<FriendlyEventType>('SINGLES'); const [format, setFormat] = useState<FriendlyFormat>('LEAGUE'); const [maxPlayers, setMaxPlayers] = useState(6); const [error, setError] = useState<string | null>(null)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const payload: CreateFriendlyMatchRequest = { title: title.trim(), description: description.trim() || null, eventType, format, maxPlayers }; const invalid = validateFriendlyMatch(payload); if (invalid) { setError(invalid); return } setError(null); try { const created = await mutation.mutateAsync(payload); navigate(friendlyDetailsPath(created.id), { state: { message: 'Friendly Match created successfully.' } }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create Friendly Match.') } }
  return <section className="mx-auto max-w-2xl px-4 py-6 sm:px-6"><h1 className="text-3xl font-black">Create Friendly Match</h1><form onSubmit={submit} className="mt-6 space-y-5 rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><label className="block font-bold">Title<input aria-label="Title" value={title} onChange={e => setTitle(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block font-bold">Description<textarea aria-label="Description" value={description} onChange={e => setDescription(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border px-4 py-3 font-normal" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="font-bold">Event Type<select aria-label="Event Type" value={eventType} onChange={e => { const value = e.target.value as FriendlyEventType; setEventType(value); setMaxPlayers(value === 'SINGLES' ? 6 : 8) }} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="SINGLES">Singles</option><option value="DOUBLES">Doubles</option></select></label><label className="font-bold">Format<select aria-label="Format" value={format} onChange={e => setFormat(e.target.value as FriendlyFormat)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="LEAGUE">League</option><option value="KNOCKOUT">Knockout</option></select></label></div><label className="block font-bold">Max Players<input aria-label="Max Players" type="number" min={eventType === 'SINGLES' ? 6 : 8} max={16} step={eventType === 'DOUBLES' ? 2 : 1} value={maxPlayers} onChange={e => setMaxPlayers(Number(e.target.value))} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}<button disabled={mutation.isPending} className="w-full rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white disabled:opacity-60">{mutation.isPending ? 'Creating...' : 'Create Friendly Match'}</button></form></section>
}
