import { useState } from 'react'
import { ApiError } from '@/api/apiClient'
import type { FriendlyFixtureData, FriendlyGameMatch, FriendlyMatch, FriendlyParticipant, FriendlyTeam } from '../types/friendly.types'
import { useCompleteFriendlyMatch, useFriendlyFixtures, useFriendlyParticipants, useFriendlyTeams, useGenerateFriendlyFixtures, useResetFriendlyFixtures, useScoreFriendlyMatch, useStartFriendlyMatch } from '../hooks/friendlyHooks'
import { unpairedFriendlyParticipants } from '../utils/friendlyTeams'
import { friendlyScoreError, isFriendlyWinningScore } from '../utils/friendlyScoring'
import { useFriendlyLiveUpdates } from '../hooks/useFriendlyLiveUpdates'
import { AnimatedScore } from '@/features/matches/components/AnimatedScore'

export const orderedFriendlyMatches = (matches: FriendlyGameMatch[]) => [...matches].sort((a, b) => a.round_number - b.round_number || a.match_number - b.match_number)
export const friendlyKnockoutRounds = (matches: FriendlyGameMatch[]) => {
  const rounds = new Map<number, FriendlyGameMatch[]>()
  for (const match of orderedFriendlyMatches(matches)) rounds.set(match.round_number, [...(rounds.get(match.round_number) ?? []), match])
  return [...rounds.entries()]
}
export const resolveFriendlyParticipant = (id: string | null, type: 'PLAYER' | 'TEAM' | null, participants: FriendlyParticipant[], teams: FriendlyTeam[]) => {
  if (!id) return { title: 'TBD', subtitle: null }
  if (type === 'PLAYER') { const player = participants.find(item => item.player_id === id); return player ? { title: player.full_name, subtitle: player.player_code } : { title: 'TBD', subtitle: null } }
  if (type === 'TEAM') { const team = teams.find(item => item.id === id); return team ? { title: team.team_code, subtitle: (team.members ?? []).map(member => member.name).join(' / ') || null } : { title: 'TBD', subtitle: null } }
  return { title: 'TBD', subtitle: null }
}

const MatchCard = ({ friendlyId, match, participants, teams, isCreator }: { friendlyId: string; match: FriendlyGameMatch; participants: FriendlyParticipant[]; teams: FriendlyTeam[]; isCreator: boolean }) => {
  const first = resolveFriendlyParticipant(match.participant1_id, match.participant1_type, participants, teams); const second = resolveFriendlyParticipant(match.participant2_id, match.participant2_type, participants, teams)
  const winner = resolveFriendlyParticipant(match.live_winner_id ?? null, match.live_winner_type ?? null, participants, teams)
  const start = useStartFriendlyMatch(friendlyId, match.id); const score = useScoreFriendlyMatch(friendlyId, match.id); const complete = useCompleteFriendlyMatch(friendlyId, match.id); const [target, setTarget] = useState<15 | 21 | 30 | ''>(''); const [error, setError] = useState<string | null>(null)
  const winning = isFriendlyWinningScore(match.participant1_score, match.participant2_score, match.winning_points); const busy = start.isPending || score.isPending || complete.isPending
  const run = async (work: () => Promise<unknown>) => { if (busy) return; setError(null); try { await work() } catch (cause) { setError(friendlyScoreError(cause instanceof Error ? cause.message : 'Unable to update match.')) } }
  const scoreControls = (side: 'A' | 'B', label: string, value: number) => <div className="mt-2 flex items-center justify-between gap-3"><button aria-label={`Decrement ${label}`} disabled={busy || value === 0} onClick={() => void run(() => score.mutateAsync({ side, action: 'DECREMENT' }))} className="h-11 w-11 rounded-xl border text-xl font-black disabled:opacity-35">−</button><b className="text-3xl tabular-nums"><AnimatedScore value={Math.max(0, value)} active={match.status === 'LIVE'} /></b><button aria-label={`Increment ${label}`} disabled={busy || winning} onClick={() => void run(() => score.mutateAsync({ side, action: 'INCREMENT' }))} className="h-11 w-11 rounded-xl bg-emerald-600 text-xl font-black text-white disabled:opacity-35">+</button></div>
  return <article className="w-full min-w-0 rounded-xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-2 text-xs text-slate-500"><span>{match.match_code}</span><strong>{match.status}</strong></div><div className="mt-3 grid gap-3"><div className="min-w-0"><p className="break-words font-bold">{first.title}</p>{first.subtitle && <p className="text-xs text-slate-500">{first.subtitle}</p>}{match.status === 'LIVE' && isCreator ? scoreControls('A', first.title, match.participant1_score) : <b className="mt-1 block text-2xl"><AnimatedScore value={Math.max(0, match.participant1_score)} active={match.status === 'LIVE'} /></b>}</div><div className="min-w-0 border-t pt-3"><p className="break-words font-bold">{second.title}</p>{second.subtitle && <p className="text-xs text-slate-500">{second.subtitle}</p>}{match.status === 'LIVE' && isCreator ? scoreControls('B', second.title, match.participant2_score) : <b className="mt-1 block text-2xl"><AnimatedScore value={Math.max(0, match.participant2_score)} active={match.status === 'LIVE'} /></b>}</div></div>{match.winning_points && <p className="mt-3 text-xs font-bold text-slate-500">Target: {match.winning_points}</p>}{isCreator && match.status === 'SCHEDULED' && match.participant1_id && match.participant2_id && <div className="mt-4 flex flex-col gap-2"><label className="text-xs font-bold">Winning points<select aria-label={`Winning points for ${match.match_code}`} value={target} onChange={event => setTarget(event.target.value ? Number(event.target.value) as 15 | 21 | 30 : '')} className="ml-2 rounded-lg border px-2 py-2"><option value="">Select</option><option value="15">15</option><option value="21">21</option><option value="30">30</option></select></label><button disabled={busy || !target} onClick={() => target && void run(() => start.mutateAsync(target))} className="rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-40">{start.isPending ? 'Starting...' : 'Start Match'}</button></div>}{match.status === 'LIVE' && winning && <p role="status" className="mt-3 rounded-lg bg-amber-50 p-3 text-xs font-bold text-amber-800">Winning score reached — complete the match or correct the score.</p>}{isCreator && match.status === 'LIVE' && <button disabled={busy || !winning} onClick={() => void run(() => complete.mutateAsync())} className="mt-3 w-full rounded-xl bg-violet-600 px-4 py-3 font-bold text-white disabled:opacity-40">{complete.isPending ? 'Completing...' : 'Complete Match'}</button>}{match.status === 'COMPLETED' && <div className="mt-3 font-bold text-violet-700"><p>Final score · Match completed</p>{match.live_winner_id && <p className="mt-1">Winner: {winner.title}</p>}</div>}{error && <p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}</article>
}

export const FriendlyFixtureView = ({ data, participants, teams, isCreator = false }: { data: FriendlyFixtureData; participants: FriendlyParticipant[]; teams: FriendlyTeam[]; isCreator?: boolean }) => data.fixture.format === 'KNOCKOUT'
  ? <div><h3 className="text-lg font-black">Knockout Bracket</h3><div data-testid="knockout-scroll" className="mt-4 flex gap-4 overflow-x-auto pb-3">{friendlyKnockoutRounds(data.matches).map(([round, matches], index, all) => <section key={round} className="w-64 shrink-0"><h4 className="mb-3 font-bold">{index === all.length - 1 ? 'Final' : `Round ${round}`}</h4><div className="grid gap-3">{matches.map(match => <MatchCard key={match.id} friendlyId={data.fixture.friendly_match_id} match={match} participants={participants} teams={teams} isCreator={isCreator} />)}</div></section>)}</div></div>
  : <div><h3 className="text-lg font-black">League Schedule</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{orderedFriendlyMatches(data.matches).map(match => <MatchCard key={match.id} friendlyId={data.fixture.friendly_match_id} match={match} participants={participants} teams={teams} isCreator={isCreator} />)}</div></div>

export const FriendlyFixturesSection = ({ match }: { match: FriendlyMatch }) => {
  const fixtureQuery = useFriendlyFixtures(match.id); const participantsQuery = useFriendlyParticipants(match.id); const teamsQuery = useFriendlyTeams(match.id, match.event_type === 'DOUBLES')
  useFriendlyLiveUpdates(match.id, fixtureQuery.data?.matches.map(item => item.id) ?? [], match.format)
  const generate = useGenerateFriendlyFixtures(match.id); const reset = useResetFriendlyFixtures(match.id); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const canManage = match.isCreator && (match.status === 'DRAFT' || match.status === 'OPEN' || match.status === 'ACTIVE')
  if (fixtureQuery.isLoading) return <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Fixtures / Schedule</h2><p className="mt-4">Loading fixtures...</p></section>
  const missing = fixtureQuery.error instanceof ApiError && fixtureQuery.error.status === 404
  const participants = participantsQuery.data ?? []; const teams = teamsQuery.data ?? []; const pairingIncomplete = match.event_type === 'DOUBLES' && !participantsQuery.isLoading && !teamsQuery.isLoading && unpairedFriendlyParticipants(participants, teams).length > 0
  const createNow = async () => { setError(null); setMessage(null); try { await generate.mutateAsync(); setMessage('Fixtures generated.'); await fixtureQuery.refetch() } catch (cause) { const text = cause instanceof Error ? cause.message : 'Unable to generate fixtures.'; if (text === 'Fixture already exists') { setMessage('Fixture already exists. Showing the current fixture.'); await fixtureQuery.refetch() } else setError(text) } }
  const resetNow = async () => { if (!window.confirm('Resetting fixtures will remove the current fixture and allow team setup changes again.')) return; setError(null); try { await reset.mutateAsync(); setMessage('Fixtures reset.'); await fixtureQuery.refetch() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to reset fixtures.') } }
  if (fixtureQuery.isError && !missing) return <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Fixtures / Schedule</h2><p role="alert" className="mt-4 text-rose-700">{fixtureQuery.error instanceof Error ? fixtureQuery.error.message : 'Unable to load fixtures.'}</p><button onClick={() => fixtureQuery.refetch()} className="mt-3 font-bold text-emerald-700 underline">Retry</button></section>
  return <section className="mobile-card rounded-3xl border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Fixtures / Schedule</h2>{canManage && fixtureQuery.data && <button disabled={reset.isPending} onClick={() => void resetNow()} className="rounded-xl border border-rose-300 px-4 py-2 text-sm font-bold text-rose-700 disabled:opacity-50">{reset.isPending ? 'Resetting...' : 'Reset Fixtures'}</button>}</div>{message && <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}{error && <p role="alert" className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{!fixtureQuery.data ? <div className="mt-4"><p className="text-slate-600">No fixture generated yet.</p>{pairingIncomplete && <p className="mt-2 text-sm text-amber-700">All approved players must be paired.</p>}{canManage && <button disabled={generate.isPending || pairingIncomplete} onClick={() => void createNow()} className="mt-4 w-full rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white disabled:opacity-50 sm:w-auto">{generate.isPending ? 'Generating...' : 'Generate Fixtures'}</button>}</div> : <div className="mt-5"><FriendlyFixtureView data={fixtureQuery.data} participants={participants} teams={teams} isCreator={canManage} /></div>}</section>
}
