import apiClient, { isExplicitMockApiMode } from '@/api/apiClient'
import { Team } from '@/features/teams/types/team.types'
import { useTeamStore } from '@/features/teams/store/teamStore'
import { usePlayerDirectoryStore } from '@/features/player/store/playerDirectoryStore'
import { useGuestPlayerStore } from '@/features/player/store/guestPlayerStore'
import { tournamentService } from '@/features/tournaments/services/tournamentService'

type WorkerTeam = { id: string; teamCode: string; tournamentId: string; categoryId: string; player1: { id: string; type: 'PLAYER' | 'GUEST' }; player2: { id: string; type: 'PLAYER' | 'GUEST' }; partnerStatus: string; status: Team['status']; createdAt: string; updatedAt?: string }

const cache = (teams: Team[]) => useTeamStore.setState({ teams })
const unsupported = (): never => { throw new Error('Teams are generated by the Worker from confirmed doubles registrations.') }
const identity = (id: string, type: 'PLAYER' | 'GUEST') => {
  const value = type === 'GUEST' ? useGuestPlayerStore.getState().getGuestById(id) : usePlayerDirectoryStore.getState().getProfileById(id)
  return { name: value?.fullName ?? 'Pending player', code: type === 'GUEST' ? (value as { guestCode?: string } | undefined)?.guestCode ?? id : (value as { playerCode?: string } | undefined)?.playerCode ?? id }
}
const fromWorker = async (raw: WorkerTeam): Promise<Team> => {
  const tournament = await tournamentService.getTournamentById(raw.tournamentId)
  const category = tournament?.categories.find((item) => item.id === raw.categoryId)
  const p1 = identity(raw.player1.id, raw.player1.type); const p2 = identity(raw.player2.id, raw.player2.type)
  return { id: raw.id, teamCode: raw.teamCode, tournamentId: raw.tournamentId, tournamentCode: tournament?.tournamentCode ?? raw.tournamentId, categoryId: raw.categoryId, categoryName: category?.name ?? raw.categoryId, player1Id: raw.player1.id, player1Code: p1.code, player1Name: p1.name, player1Type: 'FULL', player2Id: raw.player2.id, player2Code: p2.code, player2Name: p2.name, player2Type: raw.player2.type === 'GUEST' ? 'GUEST' : 'FULL', partnerStatus: raw.partnerStatus === 'PENDING_CONFIRMATION' ? 'PENDING_CONFIRMATION' : 'ACCEPTED', status: raw.status, createdAt: raw.createdAt, confirmedAt: raw.status === 'CONFIRMED' ? raw.updatedAt ?? raw.createdAt : undefined }
}
const workerTeams = async (path = '/api/teams') => {
  const data = (await apiClient.get<WorkerTeam[]>(path)).data
  const teams = await Promise.all((Array.isArray(data) ? data : []).map(fromWorker)); cache(teams); return teams
}

export const teamService = {
  createTeam: async (data: Omit<Team, 'id' | 'teamCode' | 'createdAt' | 'confirmedAt' | 'cancelledAt'>): Promise<Team> => isExplicitMockApiMode ? useTeamStore.getState().createTeam(data) : unsupported(),
  getTeams: async (): Promise<Team[]> => isExplicitMockApiMode ? useTeamStore.getState().teams : workerTeams(),
  getTeamById: async (id: string): Promise<Team | undefined> => {
    if (isExplicitMockApiMode) return useTeamStore.getState().getTeamById(id)
    const team = await fromWorker((await apiClient.get<WorkerTeam>(`/api/teams/${id}`)).data); cache([...useTeamStore.getState().teams.filter((item) => item.id !== id), team]); return team
  },
  getPlayerTeams: async (playerId: string): Promise<Team[]> => (isExplicitMockApiMode ? useTeamStore.getState().teams : await workerTeams()).filter((team) => team.player1Id === playerId || team.player2Id === playerId),
  getTournamentTeams: async (tournamentId: string): Promise<Team[]> => (isExplicitMockApiMode ? useTeamStore.getState().teams : await workerTeams()).filter((team) => team.tournamentId === tournamentId),
  getCategoryTeams: async (tournamentId: string, categoryId: string): Promise<Team[]> => (isExplicitMockApiMode ? useTeamStore.getState().teams : await workerTeams()).filter((team) => team.tournamentId === tournamentId && team.categoryId === categoryId),
  acceptPartner: async (teamId: string): Promise<Team | undefined> => isExplicitMockApiMode ? useTeamStore.getState().acceptPartner(teamId) : unsupported(),
  confirmTeam: async (teamId: string): Promise<Team | undefined> => isExplicitMockApiMode ? useTeamStore.getState().confirmTeam(teamId) : unsupported(),
  cancelTeam: async (teamId: string): Promise<Team | undefined> => isExplicitMockApiMode ? useTeamStore.getState().cancelTeam(teamId) : unsupported(),
  teamExists: async (tournamentId: string, categoryId: string, player1Id: string, player2Id: string): Promise<boolean> => (await teamService.getCategoryTeams(tournamentId, categoryId)).some((team) => (team.player1Id === player1Id && team.player2Id === player2Id) || (team.player1Id === player2Id && team.player2Id === player1Id)),
}
